package image;

public enum Image {
    EMPTY,WALL,BLINKY,PINKY,PILL,POWERPILL,FRIGHTENED_GHOST,EATEN_GHOST,MENU,BLUE_PORTAL,RED_PORTAL,PACMAN_A0,PACMAN_R1,PACMAN_R2,PACMAN_U1,PACMAN_U2,PACMAN_L1,PACMAN_L2,PACMAN_D1,PACMAN_D2;
}
