@startuml

title __IMAGE's Class Diagram__\n

  namespace image {
      enum ImageList {
        BLINKY
        BLINKY_D0
        BLINKY_D1
        ...
        RED_PORTAL
        SMALL_PANEL
        WALL
      }
      class imageList.ImageFactory {
          {static} + createImage()
          {static} - getFile()
      }
    }

  




@enduml
