@startuml

title __IMAGE's Class Diagram__\n

  namespace  {
    namespace mage {
      enum Image {
        BLINKY
        BLINKY_D0
        BLINKY_D1
        BLINKY_L0
        BLINKY_L1
        BLINKY_R0
        BLINKY_R1
        BLINKY_U0
        BLINKY_U1
        BLUE_PORTAL
        CLYDE_D0
        CLYDE_D1
        CLYDE_L0
        CLYDE_L1
        CLYDE_R0
        CLYDE_R1
        CLYDE_U0
        CLYDE_U1
        EATEN_D
        EATEN_GHOST
        EATEN_L
        EATEN_R
        EATEN_U
        EMPTY
        FRIGHTENED0
        FRIGHTENED1
        FRIGHTENED2
        FRIGHTENED3
        FRIGHTENED_GHOST
        FRUIT0
        FRUIT1
        FRUIT2
        FRUIT3
        FRUIT4
        FRUIT5
        FRUIT6
        FRUIT7
        INKY_D0
        INKY_D1
        INKY_L0
        INKY_L1
        INKY_R0
        INKY_R1
        INKY_U0
        INKY_U1
        LIFE
        MENU
        PACMAN_A0
        PACMAN_D1
        PACMAN_D2
        PACMAN_DEATH0
        PACMAN_DEATH1
        PACMAN_DEATH10
        PACMAN_DEATH2
        PACMAN_DEATH3
        PACMAN_DEATH4
        PACMAN_DEATH5
        PACMAN_DEATH6
        PACMAN_DEATH7
        PACMAN_DEATH8
        PACMAN_DEATH9
        PACMAN_L1
        PACMAN_L2
        PACMAN_R1
        PACMAN_R2
        PACMAN_U1
        PACMAN_U2
        PAUSE
        PILL
        PINKY
        PINKY_D0
        PINKY_D1
        PINKY_L0
        PINKY_L1
        PINKY_R0
        PINKY_R1
        PINKY_U0
        PINKY_U1
        POWERPILL
        RED_PORTAL
        SMALL_PANEL
        WALL
      }
    }
  }
  

  namespace  {
    namespace mage {
      class image.ImageFactory {
          {static} + createImage()
          {static} - getFile()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
